  
version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    ports:
      - '443:443'
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./.docker/nginx/local/default.conf:/etc/nginx/conf.d/default.conf
  
  # PHP Service
  php:
    depends_on:
      mysql:
        condition: service_healthy

  # MySQL Service
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: shopify
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

# Volumes
volumes:
  mysqldata:
