#!/bin/bash

# Install Composer dependencies
composer install -d "/var/www/php"

# Deal with the .env file if necessary
if [ ! -f "/var/www/php/.env" ]; then
    # Create .env file
    cat > "/var/www/php/.env" << EOF
APP_NAME=ShopifyAppV2
APP_ENV=staging
APP_KEY=base64:A0lftiesOs4CCh3aO/ab4qQe9Phj9IK6B0t4JkaB63k=
APP_DEBUG=true
APP_URL=https://shopify-app-v2-staging.payo-develop.com

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=shopifyapp-staging.csbdclrqr8bg.ap-southeast-1.rds.amazonaws.com
DB_PORT=3306
DB_DATABASE=shopifyappv2
DB_USERNAME=admin
DB_PASSWORD=UEPWuTOOqEpO6aVv36DV

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DRIVER=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

SHOPIFY_API_KEY=e0327149a1919f1f8d9ab1b1fa04bd89
SHOPIFY_API_SCOPES=read_products,write_product_listings,read_orders,write_orders
SHOPIFY_API_SECRET=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
SHOPIFY_API_VERSION=2021-07

EOF

    # Generate application key
    php "/var/www/php/artisan" key:generate --ansi
fi

chown -R www-data:www-data storage bootstrap/cache vendor
setfacl -d -m g:www-data:rw storage/logs

# Database
php "/var/www/php/artisan" migrate
